### ISSUE TITLE
ERROR: dependency ‘mcutils’ is not available for package ‘gamar’ 

### ISSUE THREAD

**Issue by jdzucker** [choisy/gamar#1]
Pb at install
ERROR: dependency ‘mcutils’ is not available for package ‘gamar’
* removing ‘/Users/jdz/Library/R/3.4/library/gamar’
Installation failed: Command failed (1)

**Comment by choisy** [comment]
I updated the DESCRIPTION file in an attempt to fix this problem. Can you pull, reinstall, and try again?

**Comment by jdzucker** [comment]
OK it works
