### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by meta00** [choisy/gamar#4]
> devtools::install_github("choisy/gamar")
Downloading GitHub repo choisy/gamar@master
from URL https://api.github.com/repos/choisy/gamar/zipball/master
Installing gamar
Downloading GitHub repo choisy/mcutils@master
from URL https://api.github.com/repos/choisy/mcutils/zipball/master
Installing mcutils
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/r8/38fxtt4j3rg2kygj6s2cx1680000gn/T/RtmpY9WNAM/devtools2f863ac260a7/choisy-mcutils-8fb868a'  \
  --library='/Library/Frameworks/R.framework/Versions/3.4/Resources/library' --install-tests 

* installing *source* package ‘mcutils’ ...
Warning in as.POSIXlt.POSIXct(x, tz) :
  unknown timezone 'zone/tz/2018c.1.0/zoneinfo/Asia/Ho_Chi_Minh'
** R
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (mcutils)
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/r8/38fxtt4j3rg2kygj6s2cx1680000gn/T/RtmpY9WNAM/devtools2f8634d1962c/choisy-gamar-971b45d'  \
  --library='/Library/Frameworks/R.framework/Versions/3.4/Resources/library' --install-tests 

* installing *source* package ‘gamar’ ...
Warning in as.POSIXlt.POSIXct(x, tz) :
  unknown timezone 'zone/tz/2018c.1.0/zoneinfo/Asia/Ho_Chi_Minh'
** R
** inst
** preparing package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘readtext’
ERROR: lazy loading failed for package ‘gamar’
* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/gamar’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/gamar’
Installation failed: Command failed (1)

**Comment by choisy** [comment]
Added readtext in the Imports field of the DESCRIPTION file. Can you test it works well by first uninstalling readtext and gamar and then try to install gamar from GitHub?

**Comment by choisy** [comment]
remove.packages(c("gamar", "readtext"))
devtools::install_github("choisy/gamar")
