### ISSUE TITLE
Bug in the examples() function that creates two levels of directory

### ISSUE THREAD

**Issue by jdzucker** [choisy/gamar#7]
aDir <- "MyPredatorExampleDir"
examples("predator-prey", aDir)
dir(aDir, recursive = TRUE)
donne cela

/Users/jdz/git/gamar/vignettes/MyPredatorExampleDir
   |-predator_prey
   |---predator_prey
   |-----includes
   |-------data
   |-------gis
   |-----models

**Comment by choisy** [comment]
Fixed.
